string(TIMESTAMP CURRENT_DATE "%Y-%m-%d" UTC)
write_file(${CUSTOM_TAGS_FILE}
	"VERSION: ${PROJECT_VERSION}" "\n"
	"NEWGRF_VERSION: ${PROJECT_VERSION}" "\n"
	"TITLE: ${PROJECT_NAME}" "\n"
	"FILENAME: ${GRF_FILE_NAME}" "\n"
	"REPO_DATE: ${CURRENT_DATE}" "\n"
)